%% Function Selection
% Choose multiple .mat files to compare critical data
clear T; close all;
path_temp = fileparts(which(mfilename));
addpath(genpath(path_temp));
clearvars path_temp; % Add subfolders to path

paths = uipickfiles;
Comparison = 'on';        %Option for comparing number of events and AQuA parameters
HotSpot = 'on';    %Option for Using both General and Moving HotSpots
SomaArea = 'on';    %Option for Getting Soma Area plot
landmarkFile = 'X:\AQuA Data\Raw Data\Original Stacks\Landmarks_Batch\cell9_LandMark.mat'; %Path and File Name of Landmark MAT File
load(landmarkFile);
imageSavePath = 'C:\Users\tomsu\Documents\GitHub\AQuA\post_AQuA'; %Path to save images generated by hotSpot

%% Loading and Extraction

file_number = numel(paths);
thresh = 50;            % Score threshold for moving events
fl = cell(1 , file_number);
names = cell(1 , file_number);
T(1:file_number) = struct('res',[],'SizeThr',[]);

for n = 1:file_number
    [p,names{n},ext] = fileparts(paths{n});
    addpath(p)
    filename = strcat(names{n},ext);
    names{n} = erase(names{n} , '_AQuA');

    dummy = load(filename);
    T(n).res = dummy.res;  % Data from all trials is stored here
    fprintf('File %i out of %i Loaded\n' , n , file_number);

    filename = string(strsplit(filename,'_'));
    filename = strsplit(filename(2),'.');
    fl(n) = {filename(1)};
    
    if ~isfield(T(n).res,'fts')
        error('Landmark was not selected during Pre-Processing');
    end
    
    rmpath(p)
    T(n).SizeThr = SizeThr(T(n).res,0);
    clear dummy
end

%% Function Calling and Use
if ~isfolder(imageSavePath)
    mkdir(imageSavePath)
end

if strcmp(Comparison , 'on') %Comparison function initiation
    trialComp(T,names);
end

if strcmp(HotSpot , 'on') %HotSpot functions initiation
    for n = 1:numel(T)
        hotSpotAll(T(n).res , imageSavePath , names{n});
        hotSpotMove(T(n).res , imageSavePath , names{n});
    end
end

if strcmp(SomaArea , 'on') %HotSpot functions initiation
    for n = 1:numel(T)
        areaCompare(T(n).res , bd0 , imageSavePath , names{n});
    end
end